[build]
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/static/css/*"
  to = "/static/css/:splat"
  status = 200

[[redirects]]
  from = "/static/js/*"
  to = "/static/js/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 